language: objective-c
xcode_project: 单元测试Demo2/单元测试Demo1.xcworkspace 
xcode_scheme: 单元测试Demo1
osx_image: xcode9.4

script:
- set -o pipefail
- xcodebuild test -project "$TRAVIS_XCODE_PROJECT" -scheme "$TRAVIS_XCODE_SCHEME" -destination "name=iPhone 7" -enableCodeCoverage YES | xcpretty

after_success:
- bash <(curl -s https://codecov.io/bash)
